options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: "Build"
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/openproject-pipeline/openproject-sync:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: "Push"
    args:
      - push
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/openproject-pipeline/openproject-sync:$COMMIT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: "Deploy"
    args:
      - gcloud
      - run
      - deploy
      - openproject-sync
      - --image
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/openproject-pipeline/openproject-sync:$COMMIT_SHA'
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --cpu
      - '1'
      - --timeout
      - 360s
      - --memory
      - 512Mi
      # Service Account from your .env file
      - --service-account
      - 'openproject-pipeline-sa@data-pipeline-475718.iam.gserviceaccount.com'
      # Environment Variables from your .env file
      - --set-env-vars
      - >
        API_TOKEN='42d5fcea4bbcbfcb1e3b26045ed5799230fb2926180a69ba5e5e5a49ada5eb40',
        BASE_URL='https://task.deepfunding.ai/',
        PROJECT_ID='$PROJECT_ID',
        DATASET_ID='openproject_data',
        GCS_BUCKET='openproject_test_bkt'
